name: ivon-experiments
channels:
  - pytorch
  - nvidia
dependencies:
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - torchtext
  - pytorch-cuda==11.8
  - pip
  - pip:
    - bayesian-torch
    - portalocker>=2.0.0
    - ivon-opt
