name: ivon-experiments
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - torchtext
  - pytorch-cuda==11.8
  - huggingface::datasets
  - tqdm
  - pip
  - pip:
    - bayesian-torch
    - portalocker>=2.0.0
    - ivon-opt==0.1.2
    - wandb
    - tiktoken
